databases:
  - name: lms-db
    databaseName: lms
    user: lms
    plan: free
    region: singapore

services:
  - type: web
    name: lms-be
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: "86400000"
      - key: DB_HOST
        fromDatabase:
          name: lms-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lms-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: lms-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: lms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: lms-db
          property: password
