spring.application.name=lms-be

# JWT
jwt.secret=${JWT_SECRET:404d635166546a576e5a7234753778214125442a472d4b6150645367566b5970}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
# active profile (default)
spring.profiles.active=dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.hiddenmethod.filter.enabled=true
# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update
