# ========================
# DATABASE
# ========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lms_dev_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Twub.0712}