# ========================
# DATABASE
# ========================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/lms_dev_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Twub.0712}